name: ototag
description: Oto Eslestirme Sistemi
publish_to: 'none'
version: 1.0.0+34

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  timezone: ^0.9.4
  http: ^1.2.0
  geolocator: ^11.0.0
  url_launcher: ^6.3.0
  image_picker: ^1.2.3
  file_picker: ^8.1.2
  flutter_local_notifications: ^17.2.3
  in_app_purchase: ^3.1.5
  geocoding: ^5.0.0
  flutter_dotenv: ^6.0.1
  onesignal_flutter: ^5.6.11
  in_app_update: ^5.0.0
  shared_preferences: ^2.5.5
  cached_network_image: ^4.0.0
  flutter_tts: ^4.0.2
  flutter_compass: ^0.8.1
  google_maps_flutter: ^2.18.1
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  firebase_core: ^4.15.0
  firebase_analytics: ^12.6.0
  firebase_crashlytics: ^5.4.0
  quick_actions: ^1.1.1
  apple_maps_flutter: ^1.4.0
  upgrader: ^13.7.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  fl_chart: ^1.2.0
  pdf: ^3.13.1
  printing: ^5.15.1
  path_provider: ^2.1.6
  open_filex: ^4.7.0
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.5.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - config.env
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700