// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1EmNB9O24q9J2v8u8Wi59Igp2wPX0bVk',
    appId: '1:73273804842:web:04e1ceab0dc9139df41b53',
    messagingSenderId: '73273804842',
    projectId: 'ototag-d6a69',
    authDomain: 'ototag-d6a69.firebaseapp.com',
    storageBucket: 'ototag-d6a69.firebasestorage.app',
    measurementId: 'G-FPGPC0EX09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe0-AOWSavOYIVqJcQWsdUDJ3mvVNxY9o',
    appId: '1:73273804842:android:2b65fa09e96643fbf41b53',
    messagingSenderId: '73273804842',
    projectId: 'ototag-d6a69',
    storageBucket: 'ototag-d6a69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs-CulXRiRMzM1juZ8y4r2s9r6ggCHmPw',
    appId: '1:73273804842:ios:b10a373555eae071f41b53',
    messagingSenderId: '73273804842',
    projectId: 'ototag-d6a69',
    storageBucket: 'ototag-d6a69.firebasestorage.app',
    iosBundleId: 'com.oto.tag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs-CulXRiRMzM1juZ8y4r2s9r6ggCHmPw',
    appId: '1:73273804842:ios:e46107293fcdc4c0f41b53',
    messagingSenderId: '73273804842',
    projectId: 'ototag-d6a69',
    storageBucket: 'ototag-d6a69.firebasestorage.app',
    iosBundleId: 'com.example.otoTamirApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1EmNB9O24q9J2v8u8Wi59Igp2wPX0bVk',
    appId: '1:73273804842:web:e52bfeb1ef5c085cf41b53',
    messagingSenderId: '73273804842',
    projectId: 'ototag-d6a69',
    authDomain: 'ototag-d6a69.firebaseapp.com',
    storageBucket: 'ototag-d6a69.firebasestorage.app',
    measurementId: 'G-9XY64K36VL',
  );
}
