<?php
require __DIR__.'/../../lib/server_configuration.php';
require __DIR__.'/../../lib/notification_delivery.php';
require __DIR__.'/../../lib/subscription_summary.php';
$pdo=new PDO('mysql:host=127.0.0.1;port=33307;charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>false]);
// Dedicated local schema; never connect this regression suite to production.
$pdo->exec('CREATE DATABASE IF NOT EXISTS ototag_notification_regression CHARACTER SET utf8mb4');
$pdo->exec('ALTER DATABASE ototag_notification_regression CHARACTER SET utf8mb4');
$pdo->exec('USE ototag_notification_regression');
foreach (['vehicle_reminder_deliveries','notification_outbox','ototag_schema_migrations','vehicles','users','notifications'] as $table) $pdo->exec("DROP TABLE IF EXISTS $table");
$pdo->exec("CREATE TABLE users(id INT PRIMARY KEY,status VARCHAR(20) DEFAULT 'active',is_suspended INT DEFAULT 0)");
$pdo->exec('CREATE TABLE vehicles(id INT PRIMARY KEY,customer_id INT,plate VARCHAR(30),inspection_date DATE,insurance_date DATE) ENGINE=InnoDB');
$pdo->exec('CREATE TABLE notifications(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,title VARCHAR(200),message TEXT) ENGINE=InnoDB');
notificationEnsureSchema($pdo);
$env=[]; $count=0;
function checkNotification($ok,$label) { global $count; if (!$ok) throw new RuntimeException('FAIL: '.$label); $count++; echo "PASS: $label\n"; }
$today=new DateTimeImmutable('2026-10-03 09:00:00',new DateTimeZone('Europe/Istanbul'));
checkNotification(!vehicleReminderScanDue(0,$today->setTime(8,59)),'reminder scan respects quiet hours');
checkNotification(vehicleReminderScanDue(0,$today),'first reminder scan is due');
checkNotification(!vehicleReminderScanDue($today->getTimestamp()-299,$today),'reminder scans are throttled');
checkNotification(vehicleReminderScanDue($today->getTimestamp()-300,$today),'edited vehicles are reconsidered within five minutes');
checkNotification(vehicleReminderScanDue($today->getTimestamp()+300,$today),'future stale scan timestamp recovers');
checkNotification(vehicleReminderPlan('2026-10-02',$today)['label']==='1 gün geçti','overdue date has accurate calendar day count');
checkNotification(vehicleReminderPlan('2026-10-03',$today)['label']==='Bugün son gün','today is not expired');
checkNotification(vehicleReminderPlan('2026-10-02 00:00:00',$today)['days']===-1,'legacy datetime deadline is handled as a calendar date');
checkNotification(vehicleReminderPlan('2026-10-18',$today)['days']===15,'15 day advance reminder');
checkNotification(vehicleReminderPlan('2026-10-19',$today)===null,'far future does not notify');
foreach (['0000-00-00','2026-02-30','',null,'bad'] as $date) checkNotification(vehicleReminderPlan($date,$today)===null,'invalid or missing dates ignored');
$pdo->exec("INSERT INTO users(id) VALUES(1),(2)");
$pdo->exec("INSERT INTO vehicles VALUES(1,1,'42 TAG 1','2026-10-02','2026-10-10'),(2,2,'42 TAG 2','2026-10-03',NULL)");
checkNotification(vehicleReminderQueue($pdo,$today->setTime(8,59))===0,'quiet hours do not notify');
checkNotification(vehicleReminderQueue($pdo,$today)===3,'closed app reminders created server side');
checkNotification(vehicleReminderQueue($pdo,$today)===0,'repeated worker does not duplicate reminders');
$pdo->exec("INSERT INTO vehicles VALUES(3,2,'42 TAG 3','2026-10-05',NULL)");
checkNotification(vehicleReminderQueue($pdo,$today->modify('+5 minutes'))===1,'vehicle added after daily scan receives a reminder');
checkNotification(vehicleReminderQueue($pdo,$today->modify('+10 minutes'))===0,'subsequent scans do not repeat new vehicle reminder');
$pdo->exec('DELETE FROM vehicles WHERE id=3');
$pdo->exec("DELETE FROM notification_outbox WHERE JSON_UNQUOTE(JSON_EXTRACT(payload,'$.data.vehicle_id'))='3'");
$pdo->exec("DELETE FROM notifications WHERE message LIKE '42 TAG 3%'");
checkNotification((int)$pdo->query('SELECT COUNT(*) FROM notifications')->fetchColumn()===3,'reminders saved to inbox');
checkNotification(vehicleReminderQueue($pdo,$today->modify('+1 day'))===1,'newly overdue reminder is emitted once');
checkNotification(vehicleReminderQueue($pdo,$today->modify('+4 days'))===1,'insurance enters 3 day warning without repeating overdue');
$ids=notificationQueue($pdo,[1,1,2,0,-1,'invalid'],'Teklif','Yeni teklif',['type'=>'bid'],'offer-1');
checkNotification(count(notificationQueue($pdo,range(1,2001),'Batch','Test',[],'large-batch'))===2,'audience beyond 2000 is chunked without losing users');
// Keep only the actual small fixture audience in subsequent send assertions.
$pdo->prepare('DELETE FROM notification_outbox WHERE event_key LIKE ?')->execute([hash('sha256','large-batch').':%']);
checkNotification(count($ids)===1 && notificationQueue($pdo,[1,2],'Teklif','Yeni teklif',[],'offer-1')===$ids,'event retry deduplicated');
$sent=[];
$transport=function($payload)use(&$sent) { $sent[]=$payload; return ['status'=>'sent','id'=>'test-push','detail'=>'Accepted']; };
$pdo->exec("UPDATE vehicles SET inspection_date='2027-01-01' WHERE id=1");
notificationDrain($pdo,100,$transport);
checkNotification((int)$pdo->query("SELECT COUNT(*) FROM notification_outbox WHERE status='cancelled'")->fetchColumn()===1,'renewed date cancels stale queued reminder');
$before=count($sent); notificationDrain($pdo,100,$transport);
checkNotification(count($sent)===$before,'sent notifications never repeated');
$payload=end($sent);
checkNotification($payload['include_aliases']['external_id']===['1','2'] && $payload['target_channel']==='push','unique authenticated external IDs target phones');
checkNotification(preg_match('/^[a-f0-9-]{36}$/D',$payload['idempotency_key'])===1,'stable UUID sent for provider deduplication');
$id=notificationQueue($pdo,[1],'Retry','Test',[],'retry')[0]; $now=time(); $keys=[];
notificationSend($pdo,$id,function($p)use(&$keys){$keys[]=$p['idempotency_key'];return ['status'=>'failed','retry_after'=>120,'detail'=>'HTTP 429'];},$now);
notificationSend($pdo,$id,function($p)use(&$keys){$keys[]=$p['idempotency_key'];return ['status'=>'sent','id'=>'retry-ok'];},$now+119);
checkNotification(count($keys)===1,'Retry-After respected');
notificationSend($pdo,$id,function($p)use(&$keys){$keys[]=$p['idempotency_key'];return ['status'=>'sent','id'=>'retry-ok'];},$now+120);
checkNotification(count($keys)===2 && $keys[0]===$keys[1],'retry uses same idempotency key');
$id=notificationQueue($pdo,[1],'No subscriber','Test',[],'no-subscriber')[0];
notificationSend($pdo,$id,function($p){return ['status'=>'no_subscribers','detail'=>'No eligible device'];});
checkNotification($pdo->query("SELECT status FROM notification_outbox WHERE id=$id")->fetchColumn()==='no_subscribers','missing push permission is not reported as delivery');
$pdo->beginTransaction(); $id=notificationQueue($pdo,[1],'Rolled back','Test',[],'rollback')[0]; $pdo->rollBack();
checkNotification(!$pdo->query("SELECT id FROM notification_outbox WHERE id=$id")->fetchColumn(),'rolled back booking cannot push');
$id=notificationQueue($pdo,[1],'Timeout','Test',[],'timeout')[0];
notificationSend($pdo,$id,function($p){throw new RuntimeException('offline');});
checkNotification($pdo->query("SELECT status FROM notification_outbox WHERE id=$id")->fetchColumn()==='failed','network error remains retryable');
$pdo->exec("UPDATE notification_outbox SET status='sending',locked_at=".($now-61).",next_attempt=0 WHERE id=$id");
notificationSend($pdo,$id,$transport,$now);
checkNotification($pdo->query("SELECT status FROM notification_outbox WHERE id=$id")->fetchColumn()==='sent','crashed worker lease can be recovered');
$user=['user_type'=>'customer','is_premium'=>1,'premium_end_date'=>'2026-10-02','obd_subscription_end_date'=>'2026-10-05'];
$summary=subscriptionSummary($user,strtotime('2026-10-03'));
checkNotification(!$summary['plans'][0]['active'] && $summary['plans'][0]['remaining_days']===0,'expired premium cannot be shown active');
checkNotification($summary['plans'][1]['active'] && $summary['plans'][1]['remaining_days']===2,'OBD remaining days from verified expiry');
$summary=subscriptionSummary(['user_type'=>'rentacar','created_at'=>'2026-09-20'],strtotime('2026-10-03'));
checkNotification($summary['plans'][0]['trial'] && $summary['plans'][1]['included'],'rentacar trial includes diagnostic access');
echo "\n$count notification and subscription checks passed.\n";
