<?php
// Builds only the explicitly isolated database and includes the booking regression.
require __DIR__.'/rental_integration_test.php';
require_once __DIR__.'/../../lib/rental_reputation.php';
$startCount=$count;
$completed=$pdo->query("SELECT j.* FROM jobs j JOIN rentacar_bids b ON b.job_id=j.id WHERE j.status='completed' AND b.status='completed' ORDER BY j.id LIMIT 1")->fetch(PDO::FETCH_ASSOC);
$customer=(int)$completed['customer_id']; $company=(int)$completed['provider_id']; $jobId=(int)$completed['id'];
$params=['job_id'=>$jobId,'rating'=>5,'comment'=>'Araç temizdi, teslim zamanında yapıldı.'];
check(callApi('get_rentacar_company_profile',1,'customer',['company_id'=>11],true)['reputation']['average']===null,'unrated firm has no fabricated five-star average');
check(callApi('get_rentacar_company_profile',1,'customer',['company_id'=>999999],true)['http']===404,'missing company returns 404');
foreach ([0,6,'2.5','abc'] as $rating) check(callApi('add_rentacar_review',$customer,'customer',array_replace($params,['rating'=>$rating]))['http']===422,'invalid stars rejected: '.$rating);
check(callApi('add_rentacar_review',$customer,'customer',array_replace($params,['comment'=>str_repeat('x',2001)]))['http']===422,'long review rejected without truncation');
check(callApi('add_rentacar_review',$customer,'customer',array_replace($params,['comment'=>['invalid']]))['http']===422,'array comment rejected as validation error');
check(callApi('add_rentacar_review',$company,'rentacar',$params)['http']===403,'firm cannot rate itself');
check(callApi('add_rentacar_review',999,'admin',$params)['http']===403,'admin cannot assign rating');
check(callApi('add_rentacar_review',3,'customer',$params)['http']===403,'unrelated customer cannot rate booking');
$pdo->exec("INSERT INTO jobs(customer_id,provider_id,service_type,status,city,agreed_price) VALUES ($customer,$company,'rentacar','completed','Konya',100)");
$unlinked=$pdo->lastInsertId();
check(callApi('add_rentacar_review',$customer,'customer',array_replace($params,['job_id'=>$unlinked]))['http']===409,'unlinked job cannot fabricate verified rental');
$pdo->exec("UPDATE jobs SET status='matched' WHERE id=$jobId");
check(callApi('add_rentacar_review',$customer,'customer',$params)['http']===409,'rating before return rejected');
$pdo->exec("UPDATE jobs SET status='cancelled' WHERE id=$jobId");
check(callApi('add_rentacar_review',$customer,'customer',$params)['http']===409,'cancelled rental cannot be rated');
$pdo->exec("UPDATE jobs SET status='completed' WHERE id=$jobId");
$a=worker('add_rentacar_review',$customer,'customer',$params+['company_id'=>11]);
$b=worker('add_rentacar_review',$customer,'customer',$params);
$first=result($a); $second=result($b);
check(in_array($first['http'],[200,201],true) && in_array($second['http'],[200,201],true),'concurrent same review requests both resolve safely');
check((int)$pdo->query("SELECT COUNT(*) FROM rental_reviews WHERE job_id=$jobId")->fetchColumn()===1,'one review per job under concurrency');
check((int)$pdo->query("SELECT company_id FROM rental_reviews WHERE job_id=$jobId")->fetchColumn()===$company,'company derived from reservation despite forged company field');
check(callApi('add_rentacar_review',$customer,'customer',$params)['http']===200,'retry returns existing review');
check(callApi('add_rentacar_review',$customer,'customer',array_replace($params,['rating'=>1]))['http']===409,'retry cannot overwrite prior rating');
$profile=callApi('get_rentacar_company_profile',3,'customer',['company_id'=>$company],true);
check($profile['reputation']['review_count']===1 && $profile['reputation']['average']==5,'profile aggregates completed rental review');
check($profile['reputation']['badge']===null,'one five-star review cannot earn badge');
check(!isset($profile['company']['phone'],$profile['reviews'][0]['customer_id']) && !array_key_exists('job_id',$profile['reviews'][0]),'public reputation excludes contact and booking identifiers');
check($profile['reviews'][0]['reviewer_name']==='Müşteri '.($customer===1?'A.':'B.') && $profile['reviews'][0]['verified_rental'],'public reviewer name is masked and verified');
check((int)$pdo->query("SELECT reviews_count FROM users WHERE id=$company")->fetchColumn()===1,'stored listing count synchronized after review');
check(callApi('get_rentacar_booking',$customer,'customer',['job_id'=>$jobId],true)['booking']['can_review']===false,'booking cannot invite duplicate rating');
check(callApi('admin_get_rental_activity',1,'customer',[],true)['http']===403,'customer cannot inspect admin activity');
check(callApi('admin_get_rental_activity',10,'rentacar',[],true)['http']===403,'firm cannot inspect competitors through activity');
check(callApi('admin_get_rental_activity',999,'admin',['stage'=>'invalid'],true)['http']===422,'admin invalid stage rejected');
$admin=callApi('admin_get_rental_activity',999,'admin',['stage'=>'completed','city'=>'Konya'],true);
check($admin['http']===200 && count($admin['bids'])>0 && !array_filter($admin['bids'],function($bid){return $bid['status']!=='completed' || $bid['city']!=='Konya';}),'admin stage and city filters match');
$detail=callApi('get_rentacar_booking',999,'admin',['job_id'=>$jobId],true);
check($detail['http']===200 && array_key_exists('complaints',$detail) && count($detail['events'])>0,'admin can inspect reservation audit and complaints');
check(!array_key_exists('events',callApi('get_rentacar_booking',$customer,'customer',['job_id'=>$jobId],true)),'customer booking cannot retrieve admin audit');
$types=$pdo->query('SELECT DISTINCT event_type FROM rental_events')->fetchAll(PDO::FETCH_COLUMN);
foreach (['listing_created','listing_updated','listing_deleted','pickup_updated','offer_placed','counter_offer','offer_closed','reserved','completed','complaint_opened','review_added'] as $type) check(in_array($type,$types,true),'audit records stage '.$type);
check((int)$pdo->query("SELECT COUNT(*) FROM rental_events WHERE event_type='review_added' AND job_id=$jobId")->fetchColumn()===1,'duplicate review creates one audit event');
$before=(int)$pdo->query('SELECT COUNT(*) FROM rental_events')->fetchColumn();
callApi('add_rentacar_review',3,'customer',$params);
check((int)$pdo->query('SELECT COUNT(*) FROM rental_events')->fetchColumn()===$before,'rejected mutation creates no audit event');

function reviewFixture($pdo,$company,$listing,$customer,$rating) {
    $pdo->prepare("INSERT INTO jobs(customer_id,provider_id,service_type,status,city,agreed_price) VALUES (?,?,'rentacar','completed','Konya',100)")->execute([$customer,$company]); $job=$pdo->lastInsertId();
    $pdo->prepare("INSERT INTO rentacar_bids(listing_id,customer_id,amount,rent_days,status,job_id,vehicle_label) VALUES (?,?,100,1,'completed',?,'Test Araç')")->execute([$listing,$customer,$job]);
    $pdo->prepare('INSERT INTO rental_reviews(job_id,company_id,customer_id,rating,comment,created_at) VALUES (?,?,?,?,?,UTC_TIMESTAMP())')->execute([$job,$company,$customer,$rating,'']);
}
// Fixture a separate company so repeat-customer weighting is measured independently.
$pdo->exec("INSERT INTO users(id,name,city,user_type) VALUES (50,'Rozet Test Firma','Konya','rentacar')");
$pdo->exec("INSERT INTO rentacar_listings(company_id,city,car_brand_model,daily_price) VALUES (50,'Konya','Test Araç',100)"); $listing=(int)$pdo->lastInsertId();
for ($id=100;$id<145;$id++) $pdo->exec("INSERT INTO users(id,name,city,user_type) VALUES ($id,'Müşteri Test','Konya','customer')");
for ($i=0;$i<25;$i++) reviewFixture($pdo,50,$listing,100,5);
$stats=rentalReviewStats($pdo,50);
check($stats['review_count']===25 && $stats['unique_customers']===1 && $stats['badge']===null,'repeat customer cannot inflate badge customer threshold');
for ($i=101;$i<105;$i++) reviewFixture($pdo,50,$listing,$i,5);
check(rentalReviewStats($pdo,50)['badge']['id']==='bronze','five distinct five-star customers earn bronze');
for ($i=105;$i<110;$i++) reviewFixture($pdo,50,$listing,$i,5);
check(rentalReviewStats($pdo,50)['badge']['id']==='silver','ten distinct customers earn silver');
for ($i=110;$i<120;$i++) reviewFixture($pdo,50,$listing,$i,5);
check(rentalReviewStats($pdo,50)['badge']['id']==='gold','twenty distinct customers earn gold');
for ($i=120;$i<140;$i++) reviewFixture($pdo,50,$listing,$i,1);
$stats=rentalReviewStats($pdo,50);
check($stats['badge']===null && $stats['badge_score']===3.0,'low verified scores remove prior badge fairly');
check($stats['distribution'][5]===44 && $stats['distribution'][1]===20,'rating distribution includes every legitimate completed review');
check(rentalRatingBadge(20,4.49999)['id']==='silver','unrounded score below gold cannot cross threshold');
check(rentalRatingBadge(4,5)===null && rentalRatingBadge(5,3.79999)===null,'sample and score thresholds both required');
$paged=callApi('get_rentacar_company_profile',1,'customer',['company_id'=>50],true);
$older=callApi('get_rentacar_company_profile',1,'customer',['company_id'=>50,'before_id'=>$paged['next_cursor']],true);
check(count($paged['reviews'])===20 && count($older['reviews'])===20 && !array_intersect(array_column($paged['reviews'],'id'),array_column($older['reviews'],'id')),'profile reviews use bounded non-overlapping pages');
$admin=callApi('admin_get_rental_activity',999,'admin',[],true);
$older=callApi('admin_get_rental_activity',999,'admin',['before_bid_id'=>$admin['next_bid_cursor']],true);
check(count($admin['bids'])===50 && count($older['bids'])>0 && !array_intersect(array_column($admin['bids'],'id'),array_column($older['bids'],'id')),'admin requests use bounded non-overlapping pages');
$statsBefore=rentalReviewStats($pdo,50);
$pdo->exec('DELETE FROM jobs WHERE customer_id=139 AND provider_id=50');
$pdo->exec('DELETE FROM users WHERE id=139');
$after=callApi('get_rentacar_company_profile',1,'customer',['company_id'=>50],true);
check($after['reputation']['review_count']===$statsBefore['review_count'] && (float)$after['reputation']['badge_score']===(float)$statsBefore['badge_score'],'account deletion cannot remove a low score and inflate reputation');
check($after['reviews'][0]['reviewer_name']==='Müşteri' && $after['reviews'][0]['verified_rental'],'deleted reviewer identity stays anonymous while historical verified score remains');
// Events from rejected authorizations never reach the committed event table.
echo '\n'.($count-$startCount)." reputation checks passed; $count combined rental checks passed.\n";
