// Dosya Yolu: lib/core/constants/car_data.dart

class CarData {
  static const Map<String, List<String>> makesAndModels = {
    "TOGG": ["T10X", "T10F"],
    "TOYOTA": ["Corolla", "Camry", "Yaris", "Yaris Cross", "RAV4", "C-HR", "Land Cruiser", "Prius", "Auris", "Avensis", "Verso", "GT86", "Supra"],
    "VOLKSWAGEN": ["Golf", "Passat", "Polo", "Tiguan", "T-Roc", "Touareg", "Taigo", "ID.3", "ID.4", "ID.5", "Jetta", "Beetle", "CC", "Scirocco", "Touran"],
    "BMW": ["1 Serisi", "2 Serisi", "3 Serisi", "4 Serisi", "5 Serisi", "7 Serisi", "8 Serisi", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "i1 / iX1", "i3", "i4", "i7", "iX3", "iX", "Z4"],
    "MERCEDES-BENZ": ["A Serisi", "B Serisi", "C Serisi", "E Serisi", "S Serisi", "CLA", "CLS", "GLA", "GLB", "GLC", "GLE", "GLS", "G Serisi", "EQA", "EQB", "EQC", "EQE", "EQS"],
    "AUDI": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "TT", "R8", "e-tron", "e-tron GT", "Q4 e-tron"],
    "RENAULT": ["Clio", "Megane", "Megane E-Tech", "Captur", "Austral", "Arkana", "Zoe", "Taliant", "Symbol", "Fluence", "Laguna", "Latitude", "Scenic", "Kadjar", "Koleos"],
    "FIAT": ["Egea", "Panda", "500", "500C", "500X", "500e", "Tipo", "Linea", "Punto", "Bravo", "Palio", "Albea"],
    "FORD": ["Focus", "Fiesta", "Puma", "Kuga", "Explorer", "Mustang", "Mustang Mach-E", "Mondeo", "Edge", "S-Max", "Galaxy", "EcoSport"],
    "HYUNDAI": ["i10", "i20", "i30", "Tucson", "Bayon", "Kona", "Ioniq 5", "Ioniq 6", "Elantra", "Accent", "Sonata", "Santa Fe"],
    "KIA": ["Picanto", "Rio", "Ceed", "Sportage", "Stonic", "Niro", "EV6", "EV9", "Cerato", "Sorento", "Carnival", "Stinger"],
    "PEUGEOT": ["208", "308", "408", "508", "2008", "3008", "5008"],
    "SKODA": ["Fabia", "Scala", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq", "Rapid", "Yeti"],
    "OPEL": ["Corsa", "Astra", "Mokka", "Crossland", "Grandland", "Insignia", "Vectra", "Zafira"],
    "NISSAN": ["Micra", "Juke", "Qashqai", "X-Trail", "Ariya", "GT-R", "370Z", "Pulsar", "Note"],
    "VOLVO": ["EX30", "EX40", "EC40", "EX90", "XC40", "XC60", "XC90", "S60", "S90", "V60", "V90"],
    "HONDA": ["Civic", "City", "Jazz", "HR-V", "CR-V", "e:Ny1", "Accord", "CR-Z", "S2000"],
    "MAZDA": ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-30", "CX-5", "CX-60", "MX-5", "RX-8"],
    "TESLA": ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
    "PORSCHE": ["911", "718 Cayman", "718 Boxster", "Cayenne", "Macan", "Panamera", "Taycan"],
    "ALFA ROMEO": ["Tonale", "Giulia", "Stelvio", "Giulietta", "Mito", "159"],
    "CUPRA": ["Formentor", "Leon", "Born", "Ateca", "Tavascan"],
    "DS AUTOMOBILES": ["DS 3", "DS 4", "DS 7", "DS 9"],
    "JEEP": ["Renegade", "Compass", "Wrangler", "Avenger", "Grand Cherokee", "Cherokee"],
    "LAND ROVER": ["Range Rover", "Range Rover Sport", "Range Rover Velar", "Range Rover Evoque", "Defender", "Discovery", "Discovery Sport"],
    "MINI": ["Cooper", "Countryman", "Clubman", "Paceman"],
    "SUBARU": ["Impreza", "XV / Crosstrek", "Forester", "Outback", "BRZ", "Levorg"],
    "SUZUKI": ["Swift", "Vitara", "S-Cross", "Jimny", "Baleno", "Grand Vitara"],
    "MITSUBISHI": ["Colt", "Space Star", "ASX", "Eclipse Cross", "Outlander", "Lancer"],
    "LEXUS": ["IS", "ES", "LS", "UX", "NX", "RX", "RZ", "LC"],
    "CHERY": ["Omoda 5", "Tiggo 7 Pro", "Tiggo 8 Pro", "Omoda 7", "Tiggo 4 Pro"],
    "MG": ["ZS", "HS", "MG4", "MG5", "Cyberster"],
    "BYD": ["Atto 3", "Seal", "Han", "Tang", "Dolphin", "Seal U"],
    "DACIA": ["Sandero", "Sandero Stepway", "Duster", "Jogger", "Spring", "Lodgy", "Logan"],
    "CITROEN": ["C3", "C3 Aircross", "C4", "C4 X", "C5 Aircross", "Ami", "C-Elysee"],
    "SEAT": ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco", "Toledo"],
    "SSANGYONG": ["Korando", "Tivoli", "Torres", "Rexton"],
    "FERRARI": ["296 GTB", "F8 Tributo", "Roma", "Portofino", "SF90 Stradale", "Purosangue"],
    "LAMBORGHINI": ["Huracan", "Revuelto", "Urus", "Aventador"],
    "MASERATI": ["Ghibli", "Quattroporte", "Levante", "Grecale", "GranTurismo", "MC20"],
    "BENTLEY": ["Continental GT", "Flying Spur", "Bentayga"],
    "ROLLS-ROYCE": ["Phantom", "Ghost", "Wraith", "Dawn", "Cullinan", "Spectre"],
    "ASTON MARTIN": ["Vantage", "DB12", "DBS", "DBX"],
    "LOTUS": ["Emira", "Eletre", "Evija"],
    "SMART": ["Fortwo", "#1", "#3"],
    "INFINITI": ["Q30", "Q50", "QX50", "QX60", "QX80"],
    "CADILLAC": ["Escalade", "XT4", "XT5", "Lyriq"],
    "CHEVROLET": ["Camaro", "Corvette", "Tahoe", "Suburban", "Captiva", "Cruze", "Aveo"],
    "DODGE": ["Challenger", "Charger", "Durango"],
    "HUMMER": ["Hummer EV"],
  };
}