name: Flutter Web Otomatik Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Kodu Çek
        uses: actions/checkout@v4

      - name: 🦋 Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 📦 Paketleri İndir
        run: |
          flutter pub upgrade
          flutter pub get

      - name: 🛠️ Web Sürümünü Derle
        run: flutter build web --release

      - name: 🚀 FTP'ye Yükle
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/web/
          server-dir: /public_html/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            api.php
            uploads/**
