name: Flutter Web Otomatik Deploy

on:
  push:
    branches:
      - main # Çalıştığınız dal adı farklıysa (örn: master) burayı değiştirin

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Kodu Çek
        uses: actions/checkout@v4

      - name: ⚙️ Java Kurulumu
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 🦋 Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 📦 Paketleri İndir
        run: flutter pub get

      - name: 🛠️ Web Sürümünü Derle
        run: flutter build web --release

      - name: 🚀 FTP'ye Yükle
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/web/
          server-dir: /public_html/ # Sunucunuzdaki klasör (httpdocs veya www ise değiştirin)
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
